# docker run -it --rm -v C:\dev\cursostec\genetic:/home gcc bash
all: client

client:
	g++ -o socketWin.o socketWin.cpp

# docker run -it --rm --net host -v C:\dev\cursostec\socketclient_c:/home gcc bash